version: '3.7'

services:
  #membuat service httpd1 dengan membuild docker image dari docker file yang ada di dalam folder public
  httpd1:
    build: ./Public1
    ports:
      - 81:80
  #membuat service httpd2 dengan membuild docker image dari docker file yang ada di dalam folder public
  httpd2:
    build: ./Public2
    ports:
      - 82:80
  #membuat service nginx 
  nginx:
    image: nginx
    #mounting konfigurasi nginx yang ada di default.conf pada host
    volumes:
    - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - httpd1
      - httpd2
    ports:
      - 80:80